"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import { WagmiProvider, createConfig, http } from "wagmi";
import { polygonZkEvmTestnet } from "viem/chains";
import { metaMask } from "wagmi/connectors";
import Web3AuthConnectorInstance from "@/utils/web3-auth-connector-instance";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Set up client
const config = createConfig({
  chains: [polygonZkEvmTestnet],
  transports: {
    [polygonZkEvmTestnet.id]: http(),
  },
  multiInjectedProviderDiscovery: false,
  connectors: [
    metaMask(),
    // walletConnect({
    //   projectId: "3314f39613059cb687432d249f1658d2",
    //   showQrModal: true,
    // }),
    Web3AuthConnectorInstance([polygonZkEvmTestnet]),
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiProvider config={config}>
          <Providers>{children}</Providers>
        </WagmiProvider>
      </body>
    </html>
  );
}
